// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmPqDKR8XEmGbL2oVekEcZOCEc44nth_s',
    appId: '1:1001243659993:web:70b1f34d9919a21eebb8c8',
    messagingSenderId: '1001243659993',
    projectId: 'appchattutor',
    authDomain: 'appchattutor.firebaseapp.com',
    storageBucket: 'appchattutor.firebasestorage.app',
    measurementId: 'G-YB0WB82LH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbVPbQ3kuXWTOemGLnJx2wP0IN86kksI',
    appId: '1:1001243659993:android:4d43df4a22deaa76ebb8c8',
    messagingSenderId: '1001243659993',
    projectId: 'appchattutor',
    storageBucket: 'appchattutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDP7PywmdkwJPNNecESsYT1ZydfHfACE',
    appId: '1:1001243659993:ios:878c043dd11e58f4ebb8c8',
    messagingSenderId: '1001243659993',
    projectId: 'appchattutor',
    storageBucket: 'appchattutor.firebasestorage.app',
    iosBundleId: 'my.id.libra.flutterTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDP7PywmdkwJPNNecESsYT1ZydfHfACE',
    appId: '1:1001243659993:ios:878c043dd11e58f4ebb8c8',
    messagingSenderId: '1001243659993',
    projectId: 'appchattutor',
    storageBucket: 'appchattutor.firebasestorage.app',
    iosBundleId: 'my.id.libra.flutterTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmPqDKR8XEmGbL2oVekEcZOCEc44nth_s',
    appId: '1:1001243659993:web:1aab237aea089a9febb8c8',
    messagingSenderId: '1001243659993',
    projectId: 'appchattutor',
    authDomain: 'appchattutor.firebaseapp.com',
    storageBucket: 'appchattutor.firebasestorage.app',
    measurementId: 'G-01Q0PXV6KZ',
  );
}
